services:
  # Apache and PHP service
  web:
    build: .  # Use the Dockerfile in the current directory
    container_name: vkrizevics-php-apache-container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - my-network

  # MySQL service
  mysql:
    image: mysql:8.0
    networks:
      - my-network
    container_name: vkrizevics-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3954895ergZCX$
      MYSQL_DATABASE: tests
      MYSQL_USER: test
      MYSQL_PASSWORD: 04dffEGRR!
    volumes:
      - ./mysql-data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - my-network
    container_name: vkrizevics-phpmyadmin-container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 3954895ergZCX$
    depends_on:
      - mysql

# Define networks
networks:
  my-network:
